[tool.poetry]
name = "eda-app"
version = "0.1.0"
description = ""
authors = ["Prashant Pandey <prashantpandeyiuet.com>"]

[tool.poetry.dependencies]
python = "^3.8" 

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
